export const COMPONENT_NAME_PLACEHOLDER = "_COMPONENT_NAME_";

export const MODULE_NAME_PLACEHOLDER = "_MODULE_NAME_";

export const MODULE_NAME_UNCAPITALIZED_PLACEHOLDER =
  "_MODULE_UNCAPITALIZED_NAME_";

export const ACTION_NAME_PLACEHOLDER = "_ACTION_NAME_";

export const SAGA_NAME_PLACEHOLDER = "_SAGA_NAME_";
